name: Auto PR Merge
on:
  #pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Try auto merge
        run: |
              urls=$(gh pr list --json url | jq -r '.[].url')
              for url in $urls; do
                  echo "Merging PR: $url"
                  gh pr merge --auto -m "$url"
              done
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
